- name: GATHER FACTS
  iosxr_facts:
    gather_network_resources: l3_interfaces

# Used to exclude L3 interfaces from ISIS for IPv6 activation

- name: VALIDATE ISIS INTERFACES
  iosxr_command:
    commands: show isis interface
  register: show_clns
  
- name: INITIALIZING VARIABLES
  set_fact:
    interfaces_to_activate: "[]"
    interface: ""
    router_id: "{{ ansible_net_interfaces.Loopback0.ipv4.address }}"

- include_tasks: l3_interface_loop.yml
  when: "'ipv4' in item"
  loop: "{{ ansible_network_resources.l3_interfaces }}"

#- name: Display all L3 interfaces
#  debug:
#    var: interfaces_to_activate
#
#- name: Display router id
#  debug:
#    var: router_id
#
- include_tasks: iosxr_isis_ldp_global.yml
- include_tasks: iosxr_isis_l3_interfaces_config.yml
  loop: "{{ interfaces_to_activate }}"